# Generated by Django 3.2.12 on 2023-01-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='name',
        ),
    ]
