# Generated by Django 3.2.12 on 2023-01-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0006_rename_created_add_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_adress',
            new_name='delivery_address',
        ),
    ]
